### PR TITLE
Fix sidebar issue

### LINKED ISSUE #9: Sidebar content is not loading on github pages
As of writing this, the github pages deployment [^1] doesn't correctly display the sidebar. When I pull the main branch and test the website locally, the sidebar looks correct:
image

For comparison, this is how it currently looks on [^1]
image

I found that if go onto a subsection, for example the "Pointers in C" section[^2], and then I refresh the page, the direct children of said sidebar element load (though not the grandchildren): (Observe how "Drills" is open, though nothing renders underneath it)
image

I was looking at the network requests made by the pages, and on the local build there was activity (via javascript) when I expanded one of the sections, however no such activity was present on the deployment website[^1]. The necessary calls were however made when in a subsection (like [^2]) and after reloading the page.

[^1]: https://cs-pub-ro.github.io/hardware-software-interface/
[^2]: https://cs-pub-ro.github.io/hardware-software-interface/Lab%201%20-%20Number%20Representation/Pointers%20in%20C/

### PR DESCRIPTION
**Pull request by george-cosma**
# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

- Fix #9

### CODE REVIEW

**Comment by george-cosma** [comment]
@gabrielmocanu I think this is fixed now? All I did was remove the double quotes around some paths with special characters ...

**Review by teodutu — CHANGES_REQUESTED** [review]
The changes seem legit. If they fix the bug, I'm fine with them after applying the changes I suggested. Apart from those, do the following to make checkpatch pass:

1. Add a description to your commit message, i.e. another line explaining what caused the error and how you fixed it.
2. Sign-off your commit by following the description here [1].
3. Reword your commit message to `infra/config: Remove double quotes". In general use imperative verbs and not the past tense of the indicative mood.
4. Use the structure "Fix #9" in your commit or PR description to automatically close #9 when this PR is merged.

[1] https://github.com/cs-pub-ro/hardware-software-interface/blob/main/CONTRIBUTING.md#commits

**Comment by george-cosma** [comment]
Done, but let it be known it was a pain in the ass to get checkpatch to not be angry. It 100% took more time than it should, and it took a lot of work to just get it to recognize the changes that were made by accepting suggestions via Github's interface. On the bright side, I got accustomed to rebaseing and force pushing (:

**Review by teodutu — APPROVED** [review]
This looks OK to me

**Pull request merged**
